# Generated by Django 5.2.4 on 2026-03-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="capacidad",
            field=models.PositiveIntegerField(default=100),
        ),
    ]
