# Generated by Django 5.2.4 on 2026-03-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_evento_capacidad"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="precio",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
