# Generated by Django 5.2.11 on 2026-05-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_evento_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='categoria',
            field=models.CharField(choices=[('Empresariales', 'Empresariales'), ('Conciertos', 'Conciertos'), ('Deportes', 'Deportes'), ('Festivales', 'Festivales')], default='Empresariales', max_length=50),
        ),
    ]
