# Generated by Django 6.0.2 on 2026-03-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_evento_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='categoria',
            field=models.CharField(choices=[('Empresariales', 'Empresariales'), ('Conciertos', 'Conciertos'), ('Deportes', 'Deportes'), ('Festivales', 'Festivales')], default='Empresariales', max_length=50),
        ),
    ]
