# Generated by Django 6.0.2 on 2026-03-24 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_evento_categoria'),
        ('tickets', '0003_add_ticket_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ticket',
            new_name='tickets_tic_codigo__69cd98_idx',
            old_name='tickets_codigo_unico_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='tickets_tic_evento__5e0653_idx',
            old_name='tickets_evento_activo_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='tickets_tic_usuario_9d18d2_idx',
            old_name='tickets_usuario_activo_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='tickets_tic_validad_251092_idx',
            old_name='tickets_validado_activo_idx',
        ),
        migrations.AddField(
            model_name='ticket',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de cancelación del ticket', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='razon_cancelacion',
            field=models.TextField(blank=True, help_text='Razón proporcionada al cancelar el ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='evento',
            field=models.ForeignKey(help_text='Evento para el cual se reservó el ticket', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.evento'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_compra',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de compra del ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario propietario del ticket', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
